config/routes.rb
Dalston::Application.routes.draw do

  match 'fine-chocolate' => 'chocolate#index', as: 'fine_chocolate'
  match 'fine-chocolate/dalston-tea-time' => 'chocolate#dalston-tea-time', as: 'dalston_tea_time'
  match 'fine-chocolate/hot-hot-hot-chocolate' => 'chocolate#hot-chocolate', as: 'hot_chocolate'
  match 'fine-chocolate/e8-chocolate' => 'chocolate#e8-chocolate', as: 'e8_chocolate'

  match 'delicate-flavours' => 'welcome#flavours.html.erb', as: 'delicate_flavours'
  match 'dalston-artist' => 'welcome#artist.html.erb', as: 'dalston_artist'

  match 'about-us' => 'pages#about-us', as: 'about_us'

  root :to => 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chocolate_controller.rb
class ChocolateController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chocolate_helper.rb
module ChocolateHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chocolate/dalston-tea-time.html.erb
tea-time

app/views/chocolate/e8-chocolate.html.erb
<%= render :partial => 'layouts/pending' %>

app/views/chocolate/hot-chocolate.html.erb
<%= render :partial => 'layouts/pending' %>

app/views/chocolate/index.html.erb
<article id="exquisite-chocolate" class="container black rounded" style="margin-bottom: 40px; padding: 20px;">
  <div class="row">
    <div class="col-md-3">
      <%= image_tag "making-chocolate-dalston-1.jpg", class: "img-responsive" %>
    </div>
    <div class="col-md-3 tk-mittwoch extra-dark">
       <span class="gold">Dark</span><br/>Belgium<br/><span class="cocoa">70% Cocoa</span>
    </div>
     <div class="col-md-3">
       <%= image_tag "making-chocolate-dalston-3.jpg", class: "img-responsive" %>
    </div>
     <div class="col-md-3 tk-mittwoch dark">
        <span class="gold">Milk</span><br/>Belgium<br/><span class="cocoa">70% Cocoa</span>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 tk-mittwoch milk">
      <span class="gold">Extra-dark</span><br/>Venezuala<br/><span class="cocoa">90% Cocoa</span>
    </div>
    <div class="col-md-3">
      <%= image_tag "making-chocolate-dalston-2.jpg", class: "img-responsive" %>
    </div>
    <div class="col-md-3 tk-mittwoch white">
      <span class="gold">White</span><br/>Belgium<br/><span class="cocoa">60% Cocoa</span>
    </div>
     <div class="col-md-3">
       <%= image_tag "making-chocolate-dalston-4.jpg", class: "img-responsive" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 call-to-action">
      <div>
      <span style="font-size: 1.6em;">Dalston Chocolate</span><br/>we make our own chocolate from the very best cocoa nibs:<br/><%= link_to 'E8 Chocolate', e8_chocolate_path %>, <%= link_to 'Dalston Tea Time', dalston_tea_time_path %> and <%= link_to 'Hot, Hot Hot Chocolate', hot_chocolate_path %>
      </div>
    </div>
  </div>
</article>

app/views/layouts/_pending.html.erb
<div class="text-center">
  <h1><%= request.path %></h1>
  <%= image_tag 'pending.gif' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Dalston</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript" src="//use.typekit.net/jlp7rqi.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>


<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to image_tag('dcs-logo-circle.gif', size: '50x50'), root_path, class: 'navbar-brand' %></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Chocolate<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li class="divider"></li>
          <li><%= link_to 'Exquisite Chocolate', fine_chocolate_path %></li>
          <li class="divider"></li>
          <li><%= link_to 'E8 Chocolate', e8_chocolate_path %></li>
          <li><%= link_to 'Dalston Tea Time', dalston_tea_time_path %></li>
          <li><%= link_to 'Hot, Hot, Hot Chocolate', hot_chocolate_path %></li>
        </ul>
      </li>
      <li><%= link_to 'Flavours', delicate_flavours_path %></a></li>
      <li><%= link_to 'Artist', dalston_artist_path %></li>
      <li><%= link_to 'About', about_us_path %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

<div id="drop-shadow" >
  <div class="container">
    <div class="row" id="header">
      <div class="col-md-12 text-center">
         <h1 class="tk-mittwoch glow"><%= link_to 'Edible Art in Chocolate', root_path, style: "color: white; text-decoration: none;"  %></h1>
         
      </div>
    </div>
  </div>
</div>

<div id="wrap">

<%= yield %>

</div><!-- end of div#wrap -->

<footer>
 &copy; dalston choclate 
</footer>

 <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-9613603-12', 'dalstonchocolate.co.uk');
    ga('send', 'pageview');

</script>


</body>
</html>

app/views/pages/about-us.html.erb
<%= render :partial => 'layouts/pending' %>

app/views/welcome/artist.html.erb
<article id="artist" class="container black rounded" style="margin-bottom: 40px; padding: 20px;">
  <div class="row">
     <div class="col-md-6 text-center">
       <%= image_tag 'artist.jpg', class: "img-responsive" %>
     </div>
     <div class="col-md-6">
      <p>Keiko has lived and worked in Dalston for over 30 years creating fine art ceramics from her studio in the <%= link_to 'old chocolate factory', "http://www.chocolatefactoryn16.com" %>.</p>
      <p>Now she makes exquisite chocolate blended with naturally dried herbs and spices grown locally.</p> 
     </div>
  </div>
  <div class="row">
    <div class="col-md-12 call-to-action">
      <div class=" tk-pragmatica-web-condensed">
         <span style="font-size: 1.2em;">Art, Chocolate &amp; Spices</span><br/>
         We grow and dry our own herbs and spices for:<br/><%= link_to 'E8 Chocolate', e8_chocolate_path %>, <%= link_to 'Dalston Tea Time', dalston_tea_time_path %> and <%= link_to 'Hot, Hot Hot Chocolate', hot_chocolate_path %>
       </div>
    </div>
  </div>
</article>

app/views/welcome/flavours.html.erb
<article id="delicate-flavours" class="container black rounded" style="margin-bottom: 40px; padding: 20px;">
  <div class="row">
     <div class="col-md-6 text-center">
       <%= image_tag 'delicate-flavours.jpg', class: 'img-responsive' %>
     </div>
     <div class="col-md-6 tk-mittwoch">
       <span class="gold">Nusturtium</span> leaf, Chocolate Tea, Peruvian <span class="chilli">Chilli</span>, <span class="gold">Shiso</span> Basil, <span class="gold">Marigold</span> Flower.
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 call-to-action">
      <div class=" tk-pragmatica-web-condensed">
         <span style="font-size: 1.4em;">Delicate Herbs and Spices</span><br/>
         We grow and dry our own herbs and spices for:<br/><%= link_to 'E8 Chocolate', e8_chocolate_path %>, <%= link_to 'Dalston Tea Time', dalston_tea_time_path %> and <%= link_to 'Hot, Hot Hot Chocolate', hot_chocolate_path %>
       </div>
    </div>
  </div>
</article>

app/views/welcome/index.html.erb
<article class="container black rounded" style="margin-bottom: 40px;">
  <div class="row">
    <div class="col-md-4 text-center">
       <a href="/fine-chocolate"><%= image_tag 'fine-chocolate.png', style: "width: 100%; max-width: 300px;" %></a>
       <h3 style="padding: 10px">exquisite <a class="litup" href="/fine-chocolate">chocolate</a></h3>
    </div>
    <div class="col-md-4 text-center">
       <h1 class="tk-mittwoch glow" style="position: relative; top: -45px; color: white;">from Dalston</h1>
       <h3>an <%= link_to 'artist', dalston_artist_path %></a></h3>
      <a href="/magical-chocolate-flavours"><%= image_tag 'keiko.gif', style: "width: 100%; max-width: 300px;" %></a>
    </div>
    <div class="col-md-4 text-center">
      <a href="/magical-chocolate-flavours"><%= image_tag 'magical-flavours.png', style: "width: 100%; max-width: 300px;" %></a>
      <h3 style="padding: 10px">delicate <%= link_to 'flavours', delicate_flavours_path %></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center black" style="padding: 0 0 20px 0;">
      <h3 class="text-center tk-mittwoch" style="font-size: 2.4em;">chocolate for <a href="#">adults</a> just <a href="">ask Keiko</a></h3>
    </div>
  </div>
</article>